CREATE TABLE CAR_MANUFACTURERS (
  MANUFACTURER_ID 	INT 			AUTO_INCREMENT PRIMARY KEY, 
  BRAND_NAME 		VARCHAR(100) 	NOT NULL, 
  ABOUT 			VARCHAR(500) 	NOT NULL, 
  ESTABLISHMENT 	VARCHAR(30) 	NOT NULL, 
  HEADQUARTER 		VARCHAR(50) 	NOT NULL,
  CREATED_AT 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP, 
  CREATED_BY 		VARCHAR(20) 
);

CREATE TABLE CAR_BODY_TYPES (
  TYPE_ID 			INT 			AUTO_INCREMENT PRIMARY KEY, 
  TYPE_NAME 		VARCHAR(100) 	NOT NULL, 
  DEFINITION 		VARCHAR(500) 	NOT NULL, 
  CREATED_AT 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP, 
  CREATED_BY 		VARCHAR(20) 
);

CREATE TABLE CAR_MODELS (
  MODEL_ID 			INT 			AUTO_INCREMENT PRIMARY KEY, 
  MODEL_NAME 		VARCHAR(100) 	NOT NULL,
  MANUFACTURER 		INT 			NOT NULL, 
  DETAILS 			VARCHAR(500) 	NOT NULL, 
  BODY_TYPE 		INT		 		NOT NULL, 
  CREATED_AT 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP, 
  CREATED_BY 		VARCHAR(20),
  
  FOREIGN KEY (MANUFACTURER) 	REFERENCES 	CAR_MANUFACTURERS(MANUFACTURER_ID),
  FOREIGN KEY (BODY_TYPE) 		REFERENCES 	CAR_BODY_TYPES(TYPE_ID)
);

